import { Geist, Geist_Mono, Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import SocketProviderWrapper from "@/provider-wrapper/SocketProviderWrapper";
import PeerProviderWrapper from "@/provider-wrapper/PeerProviderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
})

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}  ${montserrat.variable}  ${poppins.variable} h-full antialiased`}
    >
      <PeerProviderWrapper>
        <SocketProviderWrapper>
          <body className="min-h-full flex flex-col">{children}</body>
        </SocketProviderWrapper>
      </PeerProviderWrapper>
    </html>
  );
}
